version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: DOCKERFILE
    container_name: rentalcar_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rentalcardb
      SPRING_DATASOURCE_USERNAME: rentaluser
      SPRING_DATASOURCE_PASSWORD: rentalpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: rentalcar_db
    environment:
      POSTGRES_DB: rentalcardb
      POSTGRES_USER: rentaluser
      POSTGRES_PASSWORD: rentalpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
